"""phase 4a execution engine

Revision ID: 1aabb9f9b825
Revises: e15bec9321be
Create Date: 2026-08-26 10:29:15.955741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aabb9f9b825'
down_revision: Union[str, Sequence[str], None] = 'e15bec9321be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('platform_account_id', sa.String(length=200), nullable=False),
    sa.Column('platform_campaign_id', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('previous_state', sa.Text(), nullable=True),
    sa.Column('requested_state', sa.Text(), nullable=True),
    sa.Column('result_state', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], name=op.f('fk_execution_audits_approval_id_approvals')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_execution_audits_organization_id_organizations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_execution_audits_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_audits'))
    )
    with op.batch_alter_table('execution_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_audits_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_execution_audits_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('platform_account_id', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('platform_campaign_id', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('action', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('action_payload', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('requester_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('executed_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_approvals_requester_id_users'), 'users', ['requester_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_approvals_approved_by_id_users'), 'users', ['approved_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_approvals_approved_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_approvals_requester_id_users'), type_='foreignkey')
        batch_op.drop_column('executed_at')
        batch_op.drop_column('approved_by_id')
        batch_op.drop_column('requester_id')
        batch_op.drop_column('action_payload')
        batch_op.drop_column('action')
        batch_op.drop_column('platform_campaign_id')
        batch_op.drop_column('platform_account_id')
        batch_op.drop_column('platform')

    with op.batch_alter_table('execution_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_audits_organization_id'))
        batch_op.drop_index(batch_op.f('ix_execution_audits_idempotency_key'))

    op.drop_table('execution_audits')
    # ### end Alembic commands ###
