"""phase 2e hardening

Revision ID: 7478904afaa8
Revises: 5929970f87eb
Create Date: 2026-08-25 23:10:48.127521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7478904afaa8'
down_revision: Union[str, Sequence[str], None] = '5929970f87eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation_events', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_automation_events_approved_by_users'), 'users', ['approved_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_automation_events_approval_id_approvals'), 'approvals', ['approval_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_automation_events_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token_version', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('refresh_token_version')

    with op.batch_alter_table('automation_events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_automation_events_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_automation_events_approval_id_approvals'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_automation_events_approved_by_users'), type_='foreignkey')

    # ### end Alembic commands ###
