"""phase 3a platform connections

Revision ID: e15bec9321be
Revises: 7478904afaa8
Create Date: 2026-08-26 00:44:38.718716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e15bec9321be'
down_revision: Union[str, Sequence[str], None] = '7478904afaa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_platform_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('encrypted_access_token', sa.String(length=1000), nullable=True),
    sa.Column('encrypted_refresh_token', sa.String(length=1000), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('external_account_id', sa.String(length=200), nullable=True),
    sa.Column('external_account_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_ad_platform_connections_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ad_platform_connections_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ad_platform_connections'))
    )
    with op.batch_alter_table('ad_platform_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ad_platform_connections_organization_id'), ['organization_id'], unique=False)

    op.create_table('oauth_states',
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_oauth_states_organization_id_organizations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_states_user_id_users')),
    sa.PrimaryKeyConstraint('state', name=op.f('pk_oauth_states'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oauth_states')
    with op.batch_alter_table('ad_platform_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ad_platform_connections_organization_id'))

    op.drop_table('ad_platform_connections')
    # ### end Alembic commands ###
