"""add expected_previous_state

Revision ID: f48130131f55
Revises: 1aabb9f9b825
Create Date: 2026-08-26 13:26:25.641176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f48130131f55'
down_revision: Union[str, Sequence[str], None] = '1aabb9f9b825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_previous_state', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_column('expected_previous_state')

    # ### end Alembic commands ###
