import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import{BrowserRouter,NavLink,Routes,Route}from"react-router-dom";
import{LayoutDashboard,Megaphone,Palette,Wallet,ShieldCheck,FileBarChart,CheckSquare,Bot,Pause,Play,Sparkles}from"lucide-react";
import{LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer,PieChart,Pie,Cell,BarChart,Bar,Legend}from"recharts";
import"./styles.css";
const API=import.meta.env.VITE_API_URL||"http://localhost:8000";
const nav=[["/","Dashboard",LayoutDashboard],["/campaigns","Campaigns",Megaphone],["/creatives","Creatives",Palette],["/budget","Budget Automation",Wallet],["/attribution","Attribution",FileBarChart],["/approvals","Approvals",CheckSquare],["/safety","Brand Safety",ShieldCheck]];
const Card=({title,value,delta})=><div className="card kpi"><span>{title}</span><strong>{value}</strong><em>{delta}</em></div>;
function App(){return <BrowserRouter><div className="app"><aside><div className="brand"><Bot/>Ad Spend <b>Autopilot</b></div><div className="profile">AI Marketing OS<br/><small>Live optimization enabled</small></div>{nav.map(([to,label,Icon])=><NavLink key={to} to={to} className={({isActive})=>isActive?"active":""}><Icon size={18}/>{label}</NavLink>)}<div className="sidebar-bottom">● All systems operational</div></aside><main><Routes><Route path="/"element={<Dashboard/>}/><Route path="/campaigns"element={<Campaigns/>}/><Route path="/creatives"element={<Creatives/>}/><Route path="/budget"element={<Budget/>}/><Route path="/attribution"element={<Attribution/>}/><Route path="/approvals"element={<Approvals/>}/><Route path="/safety"element={<Safety/>}/></Routes></main></div></BrowserRouter>}
function CampaignTable({rows}){const[items,setItems]=useState(rows);useEffect(()=>setItems(rows),[rows]);const action=async(id,status)=>{await fetch(`${API}/campaigns/${id}/${status==="active"?"pause":"resume"}`,{method:"POST"});setItems(items.map(x=>x.id===id?{...x,status:status==="active"?"paused":"active"}:x))};return <div className="table">{items.map(c=><div className="tr"key={c.id}><div><b>{c.name}</b><small>{c.channel}</small></div><b className="green">{c.roas}x</b><span>${(c.spend||0).toLocaleString()}</span><button className="icon"onClick={()=>action(c.id,c.status)}>{c.status==="active"?<Pause size={16}/>:<Play size={16}/>}</button></div>)}</div>}
function Dashboard(){const[d,setD]=useState(null);useEffect(()=>{fetch(API+"/dashboard").then(r=>r.json()).then(setD)},[]);if(!d)return <div className="loading">Loading live performance data…</div>;let{kpis,campaigns,channel_spend,recent_events,approvals}=d;return <><header><div><h1>Dashboard</h1><p>Real-time view of ad performance and autonomous spend.</p></div><button>+ New Campaign</button></header><div className="grid kpis"><Card title="Total Spend"value={`$${kpis.total_spend.toLocaleString()}`}delta="↑ 8.4%"/><Card title="ROAS"value={kpis.roas+"x"}delta="↑ 12.6%"/><Card title="Conversions"value={kpis.conversions.toLocaleString()}delta="↑ 9.7%"/><Card title="CPA"value={`$${kpis.cpa}`}delta="↓ 7.1%"/></div><div className="grid two"><section className="card chart"><h2>Spend Over Time</h2><ResponsiveContainer width="100%"height={280}><LineChart data={campaigns.map((c,i)=>({name:"Day "+(i+1),spend:c.spend}))}><XAxis dataKey="name"/><YAxis/><Tooltip/><Line dataKey="spend"stroke="#6d5dfc"strokeWidth={3}/></LineChart></ResponsiveContainer></section><section className="card chart"><h2>Spend by Channel</h2><ResponsiveContainer width="100%"height={280}><PieChart><Pie data={channel_spend}dataKey="spend"nameKey="channel"outerRadius={95}label>{channel_spend.map((_,i)=><Cell key={i}fill={["#6d5dfc","#2bb673","#ff9f43","#3b82f6","#ef5da8"][i%5]}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer></section></div><div className="grid two"><section className="card"><h2>Top Campaigns</h2><CampaignTable rows={campaigns}/></section><section className="card"><h2>Autopilot Activity <span className="badge">{approvals} pending</span></h2>{recent_events.map((e,i)=><div className="event"key={i}><Sparkles size={16}/><div><b>{e.action}</b><small>{e.campaign}: {e.reason}</small></div></div>)}</section></div></>}
function Campaigns(){const[rows,setRows]=useState([]),[f,setF]=useState({name:"",channel:"Google Ads",audience:"General",daily_budget:1000});const load=()=>fetch(API+"/campaigns").then(r=>r.json()).then(setRows);useEffect(load,[]);const submit=async e=>{e.preventDefault();await fetch(API+"/campaigns",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(f)});setF({...f,name:""});load()};return <><header><div><h1>Campaigns</h1><p>Manage cross-channel campaigns and live guardrails.</p></div></header><div className="grid two"><section className="card"><h2>Create Campaign</h2><form onSubmit={submit}><input placeholder="Campaign name"value={f.name}onChange={e=>setF({...f,name:e.target.value})}/><select value={f.channel}onChange={e=>setF({...f,channel:e.target.value})}>{["Google Ads","Meta Ads","LinkedIn Ads","TikTok Ads"].map(x=><option key={x}>{x}</option>)}</select><input placeholder="Audience"value={f.audience}onChange={e=>setF({...f,audience:e.target.value})}/><input type="number"value={f.daily_budget}onChange={e=>setF({...f,daily_budget:+e.target.value})}/><button>Create Campaign</button></form></section><section className="card"><h2>Live Campaign List</h2><CampaignTable rows={rows}/></section></div></>}
function Creatives(){const[c,setC]=useState([]),[b,setB]=useState(null);useEffect(()=>fetch(API+"/campaigns").then(r=>r.json()).then(setC),[]);const gen=async id=>setB(await(await fetch(API+"/creative/brief",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({campaign_id:id,objective:"Increase conversions"})})).json());return <><header><div><h1>Creative Intelligence</h1><p>Turn winning messages into the next experiment.</p></div></header><div className="grid three">{c.slice(0,3).map(x=><section className="card creative"key={x.id}><div className="creative-art"></div><h3>{x.name}</h3><span className="badge">ROAS {x.roas}x</span><button onClick={()=>gen(x.id)}>Generate AI Brief</button></section>)}</div>{b&&<section className="card result"><h2>Generated Creative Brief</h2><h3>{b.campaign}</h3><p>{b.brief}</p><b>Recommended message:</b><p>{b.recommended_message}</p><ul>{b.tests.map(x=><li key={x}>{x}</li>)}</ul></section>}</>}
function Budget(){const[c,setC]=useState([]),[m,setM]=useState("");useEffect(()=>fetch(API+"/campaigns").then(r=>r.json()).then(setC),[]);const change=async x=>{let n=Number(prompt(`New daily budget for ${x.name}`,String(x.daily_budget)));if(!n)return;let r=await fetch(API+"/budget/optimize",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({campaign_id:x.id,new_daily_budget:n})});let d=await r.json();setM(d.approval_required?"Change sent for human approval.":"Budget changed automatically within guardrail.")};return <><header><div><h1>Budget Automation</h1><p>AI acts inside safe limits; larger changes require approval.</p></div></header>{m&&<div className="notice">{m}</div>}<section className="card"><h2>Budget Guardrails</h2>{c.map(x=><div className="tr"key={x.id}><div><b>{x.name}</b><small>Current daily budget</small></div><b>${x.daily_budget.toLocaleString()}</b><button onClick={()=>change(x)}>Optimize</button></div>)}</section></>}
function Attribution(){const[d,setD]=useState([]);useEffect(()=>fetch(API+"/reports/attribution").then(r=>r.json()).then(setD),[]);return <><header><div><h1>Attribution Report</h1><p>Weekly cross-channel performance summary.</p></div><button>Export CSV</button></header><section className="card chart"><ResponsiveContainer width="100%"height={360}><BarChart data={d}><XAxis dataKey="channel"/><YAxis/><Tooltip/><Legend/><Bar dataKey="conversions"fill="#6d5dfc"/><Bar dataKey="revenue"fill="#2bb673"/></BarChart></ResponsiveContainer></section></>}
function Approvals(){const[d,setD]=useState([]),load=()=>fetch(API+"/approvals").then(r=>r.json()).then(setD);useEffect(load,[]);const decide=async(id,decision)=>{await fetch(`${API}/approvals/${id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({decision})});load()};return <><header><div><h1>Approvals</h1><p>Human-in-the-loop control for high-impact actions.</p></div></header><section className="card">{d.map(a=><div className="approval"key={a.id}><div><b>{a.summary}</b><small>Requested by {a.requested_by} · Impact ${a.impact.toLocaleString()}</small></div>{a.status==="pending"?<div><button onClick={()=>decide(a.id,"approved")}>Approve</button><button className="danger"onClick={()=>decide(a.id,"rejected")}>Reject</button></div>:<span className="badge">{a.status}</span>}</div>)}</section></>}
function Safety(){const[t,setT]=useState(""),[r,setR]=useState(null);const review=async()=>setR(await(await fetch(API+"/brand-safety/review",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:t})})).json());return <><header><div><h1>Brand Safety</h1><p>Run copy through policy and risk checks before publishing.</p></div></header><section className="card"><textarea rows="8"placeholder="Paste ad copy here…"value={t}onChange={e=>setT(e.target.value)}/><button onClick={review}>Review Copy</button>{r&&<div className={"result "+(r.safe?"safe":"unsafe")}><h3>{r.recommendation}</h3><p>{r.safe?"No flagged terms found.":"Flags: "+r.flags.join(", ")}</p></div>}</section></>}
createRoot(document.getElementById("root")).render(<App/>);
